### PR TITLE
Fix/291 cannot find list of containers belonging to a group

### LINKED ISSUE #291: cannot find list of containers belonging to a group
## Bug Description

cannot find the list of containers belonging to a group.

## Steps to Reproduce

1. register new user through Cognito UI
2. GET `/groups/{groupId}/containers` or `containers`
3. See the containers list result is empty

## Expected Behavior

can get the list of containers belonging to a group.

## Screenshots

In the DynamoDB, This kind of data looks missing.
PK={GroupId} & SK=Container#{ContainerId}
image

## Additional Context

I couldn't see the details of this problem yet.

### PR DESCRIPTION
**Pull request by taniguchiiqqq**
## Overviews of implementation
When a container is created, the group is updated to include the container ID.
I should have updated the Group following the creation of a container.

### CODE REVIEW

File: backend/main/src/Group/UseCases/CreateContainerUseCase/CreateContainerUseCase.ts [hunk 1]
```diff
@@ -75,7 +75,15 @@ export class CreateContainerUseCase
...
 
+		const newGroupOrError = group.addContainerId(containerId);
+		if (!newGroupOrError.ok) {
+			return Err(newGroupOrError.error);
+		}
+		const newGroup = newGroupOrError.value;
+
 		await this.containerRepository.create(container);
+		// add containerId to the Group
+		await this.groupRepository.create(newGroup);
```
Comment (hitohata) [inline backend/main/src/Group/UseCases/CreateContainerUseCase/CreateContainerUseCase.ts]: Do we need to process this line with blocking?

Comment (hitohata) [reply backend/main/src/Group/UseCases/CreateContainerUseCase/CreateContainerUseCase.ts]: I think 'update' is more appropriate than 'create' in the group repository in this situation.

**Review by hitohata — APPROVED** [review]
Thank you for resolving this bug. I've left some comments but it's not mandatory to fix.

File: backend/main/src/Group/UseCases/CreateContainerUseCase/CreateContainerUseCase.ts (hunk 1 above)
Comment (taniguchiiqqq) [reply backend/main/src/Group/UseCases/CreateContainerUseCase/CreateContainerUseCase.ts]: Thank you for your comments! Both comments totally make sense. so I've fixed them.
